sudo: false

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7

install:
  - npm install -g jshint
  # Upgrade to latest setuptools to avoid this issue:
  # https://github.com/pypa/setuptools/issues/951
  - pip install -U setuptools
  - pip install -r requirements.txt

script: make
